In [2]:
import numpy as np
import sympy as sym

In [3]:
def GetLaguerre(n):
    
    x = sym.Symbol('x',Real=True)
    y = sym.Symbol('y',Real=True)
    
    y = sym.exp(-x)*x**n
    
    p = sym.exp(x)*sym.diff(y,x,n)/(np.math.factorial(n))
    
    return p

In [4]:
Laguerre = []

n=20
for i in range(n+1):
    Laguerre.append(GetLaguerre(i))

In [5]:
def Derivative(f,x,h=1e-6):
    return (f(x+h)-f(x-h))/(2*h)

In [6]:
def GetNewtonMethod(f,df,xn,itmax=1000,precision=1e-5):
    
    error = 1
    it=0
    
    while error > precision and it < itmax:
        
        try:
            
            xn1 = xn - f(xn)/df(f,xn)
            error = np.abs(f(xn)/df(f,xn))
            
        except ZeroDivisionError:
            print('Division por cero')
            
        xn = xn1
        it += 1
    
    if it == itmax:
        return False
    else:
        return xn

In [7]:
def GetAllRoots(x,tolerancia=8):
    
    Roots = np.array([])
    
    for i in x:
        root = GetNewtonMethod(f,Derivative,i)
        
        if root != False:
            
            croot = np.round( root, tolerancia )
            
            if croot not in Roots:
                Roots = np.append(Roots,croot)
                
    Roots.sort()
    
    return Roots

In [10]:
x = sym.Symbol('x',Real=True)
xtrial = np.linspace(0,100,200)
print('La raiz del polinomio de grado 0 de Laguerre no existe \n')
print('La raiz del polinomio de grado 1 de Laguerre es: \n1 \n')
for i in range(2,n+1):
    func=Laguerre[i]
    f= sym.lambdify([x],func,'numpy')
    Roots = GetAllRoots(xtrial)
    print('Las raices del polinomio de grado %i de Laguerre son:'%i)
    print(Roots,'\n')

La raiz del polinomio de grado 0 de Laguerre no existe 

La raiz del polinomio de grado 1 de Laguerre es: 
1 

Las raices del polinomio de grado 2 de Laguerre son:
[0.58578644 3.41421356] 

Las raices del polinomio de grado 3 de Laguerre son:
[0.41577456 2.29428036 6.28994508] 

Las raices del polinomio de grado 4 de Laguerre son:
[0.32254769 1.7457611  4.5366203  9.39507091] 

Las raices del polinomio de grado 5 de Laguerre son:
[ 0.26356032  1.41340306  3.59642577  7.08581001 12.64080084] 

Las raices del polinomio de grado 6 de Laguerre son:
[ 0.2228466   1.1889321   2.99273633  5.77514357  9.83746742 15.98287398] 

Las raices del polinomio de grado 7 de Laguerre son:
[ 0.19304368  1.0266649   2.56787674  4.90035308  8.18215344 12.73418029
 19.39572786] 

Las raices del polinomio de grado 8 de Laguerre son:
[ 0.17027963  0.90370178  2.25108663  4.26670017  7.0459054  10.75851601
 15.74067864 22.86313174] 

Las raices del polinomio de grado 9 de Laguerre son:
[ 0.15232223  0.80722002