In [ ]:
import numpy as np
import sympy as sym

In [ ]:
def GetLegendre(n):
    
    x = sym.Symbol('x',Real=True)
    y = sym.Symbol('y',Real=True)
    
    y = (x**2-1)**n
    p = sym.diff(y,x,n)/(2**n * np.math.factorial(n))
    
    return p

In [ ]:
Legendre = []

n=20
for i in range(n+1):
    Legendre.append(GetLegendre(i))

In [ ]:
def Derivative(f,x,h=1e-6):
    return (f(x+h)-f(x-h))/(2*h)

In [ ]:
def GetNewtonMethod(f,df,xn,itmax=1000,precision=1e-5):
    
    error = 1
    it=0
    
    while error > precision and it < itmax:
        
        try:
            
            xn1 = xn - f(xn)/df(f,xn)
            error = np.abs(f(xn)/df(f,xn))
            
        except ZeroDivisionError:
            print('Division por cero')
            
        xn = xn1
        it += 1
    
    if it == itmax:
        return False
    else:
        return xn

In [ ]:
def GetAllRoots(x,tolerancia=8):
    
    Roots = np.array([])
    
    for i in x:
        root = GetNewtonMethod(f,Derivative,i)
        
        if root != False:
            
            croot = np.round( root, tolerancia )
            
            if croot not in Roots:
                Roots = np.append(Roots,croot)
                
    Roots.sort()
    
    return Roots

In [9]:
x = sym.Symbol('x',Real=True)
xtrial = np.linspace(-1,1,100)
print('La raiz del polinomio de grado 0 de Legendre no existe \n')
print('La raiz del polinomio de grado 1 de Legendre es: \n 0 \n')
for i in range(2,n+1):
    func=Legendre[i]
    f= sym.lambdify([x],func,'numpy')
    Roots = GetAllRoots(xtrial)
    print('Las raices del polinomio de grado %i de Legendre son:'%i)
    print(Roots,'\n')

La raiz del polinomio de grado 0 de Legendre no existe 

La raiz del polinomio de grado 1 de Legendre es: 
 0 

Las raices del polinomio de grado 2 de Legendre son:
[-0.57735027  0.57735027] 

Las raices del polinomio de grado 3 de Legendre son:
[-0.77459667  0.          0.77459667] 

Las raices del polinomio de grado 4 de Legendre son:
[-0.86113631 -0.33998104  0.33998104  0.86113631] 

Las raices del polinomio de grado 5 de Legendre son:
[-0.90617985 -0.53846931  0.          0.53846931  0.90617985] 

Las raices del polinomio de grado 6 de Legendre son:
[-0.93246951 -0.66120939 -0.23861919  0.23861919  0.66120939  0.93246951] 

Las raices del polinomio de grado 7 de Legendre son:
[-0.94910791 -0.74153119 -0.40584515  0.          0.40584515  0.74153119
  0.94910791] 

Las raices del polinomio de grado 8 de Legendre son:
[-0.96028986 -0.79666648 -0.52553241 -0.18343464  0.18343464  0.52553241
  0.79666648  0.96028986] 

Las raices del polinomio de grado 9 de Legendre son:
[-0.96816024 -